spring:
  application:
    name: application

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/voters_db"
    username: "root"
    password: "root@123"



logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "Citizen Service Portal"
    description: "This service is used to register, authenticate citizens for casting votes"
