spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/candidatesdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
management:
 endpoints:
   web:
     exposure:
       include: "*"
 info:
   env:
     enabled: True
info:
 app:
   name :  "Polling Service"
   description: "This this service handles candiadtes and voting to candidates."


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 


