spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/candidatesdb
    username: root
    password: root@123
management:
 endpoints:
   web:
     exposure:
       include: "*"
 info:
   env:
     enabled: True
info:
 app:
   name :  "My First Spring Boot app"
   description: "This is super demo appliction of springboot"



